// arc4.cpp - originally written and placed in the public domain by Wei Dai

// The ARC4 algorithm was first revealed in an anonymous email to the
// cypherpunks mailing list. This file originally contained some
// code copied from this email. The code has since been rewritten in order
// to clarify the copyright status of this file. It should now be
// completely in the public domain.

#include "pch.h"
#define CRYPTOPP_ENABLE_NAMESPACE_WEAK 1
#include "arc4.h"

NAMESPACE_BEGIN(CryptoPP)
namespace Weak1 {

#if defined(CRYPTOPP_DEBUG) && !defined(CRYPTOPP_DOXYGEN_PROCESSING)
/**
 * @brief Instantiates an ARC4 object for compile-time or debug-time testing.
 *
 * This function is intended for internal use to ensure that the ARC4 class can be instantiated without errors.
 */
void ARC4_TestInstantiations()
{
	ARC4 x;
}
#endif

/**
 * @brief Destroys the ARC4_Base object and resets internal indices.
 *
 * Sets the internal state indices to zero upon object destruction.
 */
ARC4_Base::~ARC4_Base()
{
	m_x = m_y = 0;
}

/**
 * @brief Initializes the ARC4 state with the provided key and parameters.
 *
 * Sets up the internal state array using the ARC4 key-scheduling algorithm (KSA) based on the given key. After initialization, discards a configurable number of initial keystream bytes as specified by the parameters to enhance security.
 *
 * @param key Pointer to the key bytes.
 * @param length Length of the key in bytes.
 * @param params Parameters that may specify the number of initial keystream bytes to discard ("DiscardBytes").
 */
void ARC4_Base::UncheckedSetKey(const byte *key, unsigned int length, const NameValuePairs &params)
{
	AssertValidKeyLength(length);

	m_x = 1;
	m_y = 0;

	unsigned int i;
	for (i=0; i<256; i++)
		m_state[i] = byte(i);

	unsigned int keyIndex = 0, stateIndex = 0;
	for (i=0; i<256; i++)
	{
		unsigned int a = m_state[i];
		stateIndex += key[keyIndex] + a;
		stateIndex &= 0xff;
		m_state[i] = m_state[stateIndex];
		m_state[stateIndex] = byte(a);
		if (++keyIndex >= length)
			keyIndex = 0;
	}

	int discardBytes = params.GetIntValueWithDefault("DiscardBytes", GetDefaultDiscardBytes());
	DiscardBytes(discardBytes);
}

template <class T>
/**
 * @brief Generates one byte of ARC4 keystream and updates internal state.
 *
 * Performs a single step of the ARC4 pseudo-random generation algorithm (PRGA), updating the indices and state array, and returns the next keystream byte.
 *
 * @tparam T Type of the state indices (typically byte or unsigned int).
 * @param x Reference to the first state index, updated in place.
 * @param y Reference to the second state index, updated in place.
 * @param s Pointer to the 256-byte ARC4 state array, modified in place.
 * @return unsigned int The next keystream byte.
 */
static inline unsigned int MakeByte(T &x, T &y, byte *s)
{
	unsigned int a = s[x];
	y = byte((y+a) & 0xff);
	unsigned int b = s[y];
	s[x] = byte(b);
	s[y] = byte(a);
	x = byte((x+1) & 0xff);
	return s[(a+b) & 0xff];
}

/**
 * @brief Fills the output buffer with keystream bytes generated by the ARC4 algorithm.
 *
 * Generates a block of keystream data of the specified size and writes it to the provided output buffer.
 *
 * @param output Pointer to the buffer where the keystream bytes will be written.
 * @param size Number of keystream bytes to generate.
 */
void ARC4_Base::GenerateBlock(byte *output, size_t size)
{
	while (size--)
		*output++ = static_cast<byte>(MakeByte(m_x, m_y, m_state));
}

/**
 * @brief Encrypts or decrypts data using the ARC4 stream cipher.
 *
 * XORs the input data with the ARC4 keystream, writing the result to the output buffer. Supports in-place processing if input and output buffers are the same.
 *
 * @param outString Pointer to the output buffer.
 * @param inString Pointer to the input buffer.
 * @param length Number of bytes to process.
 */
void ARC4_Base::ProcessData(byte *outString, const byte *inString, size_t length)
{
	if (length == 0)
		return;

	byte *const s = m_state;
	unsigned int x = m_x;
	unsigned int y = m_y;

	if (inString == outString)
	{
		do
		{
			*outString++ ^= MakeByte(x, y, s);
		} while (--length);
	}
	else
	{
		do
		{
			*outString++ = *inString++ ^ byte(MakeByte(x, y, s));
		}
		while(--length);
	}

	m_x = byte(x);
	m_y = byte(y);
}

/**
 * @brief Advances the ARC4 keystream by discarding a specified number of bytes.
 *
 * Skips `n` bytes of the keystream without producing output, updating the internal state as if those bytes had been generated.
 *
 * @param n Number of keystream bytes to discard.
 */
void ARC4_Base::DiscardBytes(size_t n)
{
	if (n == 0)
		return;

	byte *const s = m_state;
	unsigned int x = m_x;
	unsigned int y = m_y;

	do
	{
		MakeByte(x, y, s);
	}
	while(--n);

	m_x = byte(x);
	m_y = byte(y);
}

}
NAMESPACE_END
