// blumshub.cpp - originally written and placed in the public domain by Wei Dai

#include "pch.h"
#include "blumshub.h"
#include "integer.h"

NAMESPACE_BEGIN(CryptoPP)

/**
 * @brief Initializes the Blum Blum Shub pseudorandom generator with a modulus and seed.
 *
 * Sets up the internal state using the provided modulus `n` and seed value, preparing the generator for pseudorandom bit output.
 *
 * @param n The modulus for the generator, typically the product of two large primes.
 * @param seed The initial seed value for the generator.
 */
PublicBlumBlumShub::PublicBlumBlumShub(const Integer &n, const Integer &seed)
	: modn(n),
	  current(modn.Square(modn.Square(seed))),
	  maxBits(BitPrecision(n.BitCount())-1),
	  bitsLeft(maxBits)
{
}

/**
 * @brief Generates a single pseudorandom bit using the Blum Blum Shub algorithm.
 *
 * @return unsigned int The next pseudorandom bit (0 or 1).
 */
unsigned int PublicBlumBlumShub::GenerateBit()
{
	if (bitsLeft==0)
	{
		current = modn.Square(current);
		bitsLeft = maxBits;
	}

	return static_cast<unsigned int>(current.GetBit(--bitsLeft));
}

/**
 * @brief Generates a pseudorandom byte using the Blum Blum Shub algorithm.
 *
 * Combines eight pseudorandom bits, generated sequentially, into a single byte.
 * @return byte A pseudorandom byte.
 */
byte PublicBlumBlumShub::GenerateByte()
{
	byte b=0;
	for (int i=0; i<8; i++)
		b = byte((b << 1) | PublicBlumBlumShub::GenerateBit());
	return b;
}

/**
 * @brief Fills a buffer with pseudorandom bytes generated by the Blum Blum Shub algorithm.
 *
 * @param output Pointer to the buffer to be filled.
 * @param size Number of bytes to generate.
 */
void PublicBlumBlumShub::GenerateBlock(byte *output, size_t size)
{
	while (size--)
		*output++ = PublicBlumBlumShub::GenerateByte();
}

/**
 * @brief Encrypts or decrypts data by XORing with pseudorandom bytes.
 *
 * Processes the input buffer by XORing each byte with a pseudorandom byte generated by the Blum Blum Shub algorithm, storing the result in the output buffer. This can be used for simple stream cipher encryption or decryption.
 */
void PublicBlumBlumShub::ProcessData(byte *outString, const byte *inString, size_t length)
{
	while (length--)
		*outString++ = *inString++ ^ PublicBlumBlumShub::GenerateByte();
}

/**
 * @brief Constructs a Blum Blum Shub pseudorandom generator with specified primes and seed.
 *
 * Initializes the generator using primes `p` and `q` (where the modulus is `p*q`) and a seed value. The initial state is set to the square of the seed modulo `p*q`.
 */
BlumBlumShub::BlumBlumShub(const Integer &p, const Integer &q, const Integer &seed)
	: PublicBlumBlumShub(p*q, seed),
	  p(p), q(q),
	  x0(modn.Square(seed))
{
}

/**
 * @brief Advances the generator state to the specified byte position.
 *
 * Updates the internal state so that subsequent output begins at the bit position corresponding to the given byte index, allowing for random access within the pseudorandom sequence.
 *
 * @param index The byte position to seek to in the output stream.
 */
void BlumBlumShub::Seek(lword index)
{
	Integer i(Integer::POSITIVE, index);
	i *= 8;
	Integer e = a_exp_b_mod_c (2, i / maxBits + 1, (p-1)*(q-1));
	current = modn.Exponentiate(x0, e);
	bitsLeft = maxBits - i % maxBits;
}

NAMESPACE_END
